MODEL:
  META_ARCHITECTURE: "GeneralizedRCNN"
  WEIGHT: "https://s3-us-west-2.amazonaws.com/detectron/ImageNetPretrained/FBResNeXt/X-101-64x4d.pkl"
  BACKBONE:
      CONV_BODY: "R-101-FPN"
      OUT_CHANNELS: 512
  RPN:
    USE_FPN: True
    ANCHOR_STRIDE: (4, 8, 16, 32, 64)
  ROI_HEADS:
    USE_FPN: True
  ROI_BOX_HEAD:
    POOLER_RESOLUTION: 7
    POOLER_SCALES: (0.25, 0.125, 0.0625, 0.03125)
    POOLER_SAMPLING_RATIO: 2
    FEATURE_EXTRACTOR: "FPN2MLPFeatureExtractor"
    RETURN_FC_FEATS: True
    PREDICTOR: "FPNPredictor"
    MLP_HEAD_DIM: 2048
    NUM_CLASSES: 1601
    # VQA GENOME SPECIFIC STUFF
    ATTR: True
  RESNETS:
    STRIDE_IN_1X1: False
    NUM_GROUPS: 64
    WIDTH_PER_GROUP: 4
DATASETS:
  TRAIN: ("visual_genome_train", "visual_genome_val")
  TEST: ("visual_genome_val",)
DATALOADER:
  NUM_WORKERS: 8
SOLVER: 
  BASE_LR: 0.01
  MAX_ITER: 180000
  STEPS: (120000, 160000)
  IMS_PER_BATCH: 8
  CHECKPOINT_PERIOD: 20000
  WEIGHT_DECAY: 0.0001
